# Generated by Django 2.2.8 on 2020-09-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0002_auto_20200919_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
